# Generated by Django 4.2.4 on 2023-08-22 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Camiseta',
        ),
    ]
