# Generated by Django 4.2.4 on 2023-08-22 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_task_camiseta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Camiseta',
            new_name='Camisetas',
        ),
    ]
