# Generated by Django 4.2.4 on 2023-08-22 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_camiseta_camisetas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Camisetas',
            new_name='Camiseta',
        ),
    ]
