# Generated by Django 4.2.4 on 2023-08-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_camisetas_camiseta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camiseta',
            name='imagen',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
