# Generated by Django 4.2.4 on 2023-08-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_camiseta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camiseta',
            name='imagen',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
